language: generic

sudo: required

#services:
#  - docker

#before_install:
#  - docker build -t ouchcs/django-test -f ./server_dev/Dockerfile.dev ./server_dev
#
#script:
#  - docker run -e CI=true ouchcs/django-test python3 manage.py test

before_deploy:
  - zip -r django-docker-server *
  - mkdir -p deploy
  - mv django-docker-server.zip deploy/django-docker-server.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: server-dev-bucket
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: Funbucket/django-docker-server
      branch: main
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: server-dev-bucket
    key: django-docker-server.zip
    bundle_type: zip
    application: server-dev-codeDeploy-service
    deployment_group: server-dev-codeDeploy-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: Funbucket/django-docker-server
      branch: main
    
