version: '3'
services:
  django:
    build:
      context: ./server_dev
      dockerfile: Dockerfile
    container_name: django
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ./server_dev:/srv/server_dev
      - ./log:/var/log/uwsgi

  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - ./log:/var/log/nginx
