version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - ./server_dev:/srv/server_dev
      - ./log:/var/log/nginx
