version: '3'
services:
  django:
    build:
      context: ./server_dev
      dockerfile: Dockerfile
    command: uwsgi --http :8001 uwsgi.ini
    volumes:
      - ./server_dev:/srv/server_dev
      - ./log:/var/log/uwsgi
    ports:
      - "8001:8000"
