version: '3'
services:
  django:
    build:
      context: ../server_dev
      dockerfile: Dockerfile.dev
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - ../server_dev:/srv/server_dev
